### ISSUE TITLE
Adaptar funcionalidades del sistema

### ISSUE THREAD

**Issue by magscorb** [eduardoTIS2/Prueba#2]
Quitar información basura y adaptar las funcionalidades para el sistema de reservación de eventos.

**Comment by eduardoTIS2** [comment]
![casos de uso del negocio](https://cloud.githubusercontent.com/assets/17857502/15306482/7b765020-1b90-11e6-962c-c4d055d652e0.png)

**Comment by eduardoTIS2** [comment]
![diagrama de casos de uso](https://cloud.githubusercontent.com/assets/17857502/15306517/bc766434-1b90-11e6-9c0b-516c7c6aa0c4.png)
